# create_user_with_ssh.yml
---
- hosts: all
  become: yes
  tasks:
    - name: Add user
      user:
        name: "{{ new_user }}"
        state: present
        shell: /bin/bash

    - name: Create .ssh directory
      file:
        path: "/home/{{ new_user }}/.ssh"
        state: directory
        owner: "{{ new_user }}"
        group: "{{ new_user }}"
        mode: '0700'

    - name: Add SSH key
      authorized_key:
        user: "{{ new_user }}"
        key: "{{ ssh_public_key }}"
        state: present

